### ISSUE TITLE
Compiling the docs - what dependencies are there?

### ISSUE THREAD

**Issue by kozross** [robert-strandh/McCLIM#10]
What do I need (besides a TeX distro) to compile the documentation? So far, I haven't had much luck.

**Comment by spaceotter** [comment]
Yeah, it's not obvious if quicklisp provides precompiled documentation. That's how I got McCLIM. The documentation build fails for me because "texinfo.tex" is missing.

**Comment by gabriel-laddel** [comment]
I can't speak to the "texinfo.tex" bug, but .../McCLIM/Doc/Guided-Tour/ fails in an obvious manner (on my particular distro) with the error message "fig2dev missing".  Install it and everything works swimmingly. If one is on gentoo, then this is part of the package media-gfx/transfig.

The file produced is a .dvi, but one can get a .pdf using pdflatex on .../McCLIM/Doc/Guided-Tour/guided-tour.tex

The /Doc/ build fails indicating that uniconverter is missing. For whatever reason, one of the required ebuilds (media-libs/lcms-1.19-r1) is currently failing to build (can't find a mirror or some such).

I can't build uniconverter from the sourceforge tarball either as it has problems (some nonsense about tabs vs. spaces and python being dependent on that for semantics).

**Comment by TeMPOraL** [comment]
If someone can make this work, why not add a PDF to the repo?

**Comment by dkochmanski** [comment]
standard tools from the repository (latex, fig2dev etc) are needed. In case of texinfo makeinfo is necessary.
