### ISSUE TITLE
Raster Image Backend

### ISSUE THREAD

**Issue by gas2serra** [robert-strandh/McCLIM#107]
Hi All,
I'm developing a new backend to draw into raster image files (like postscript backend). It also can draw to climi::rgb-image.
It uses:
- cl-vectors for rendering
- opticl or zpng for saving

You can find a first dirty version in png branch of git@github.com:gas2serra/McCLIM.git.
Considering that it is not a part of clim 2.0 specification, do you think it can be an useful extension to add to McClim project?

Alessandro

**Comment by dkochmanski** [comment]
I think this will be a very useful extension for McCLIM. Will it be useful as basis for framebuffer backend in the future?

**Comment by dkochmanski** [comment]
Regarding it's differences from clim specification, I think that it is important to have a documentation for it.

**Comment by gas2serra** [comment]
I think it will be possible to use it for a framebuffer backend. The major problem is that it is really slow. At the moment, my goal is to have a full featured and really simple rendering engine. 
Then, may be, we can try to optimize it.

**Comment by dkochmanski** [comment]
Merged in master
