### ISSUE TITLE
Trouble with examples

### ISSUE THREAD

**Issue by spaceotter** [robert-strandh/McCLIM#11]
If I bring up the Listener and go to Filesystem -> Change directory and get completions in a sufficiently full directory, the completions cover up the prompt and won't go away.

Also, the font example crashes.
FONT-ERROR in current request  Code 47.0 [QueryFont] ID #x680016E
   [Condition of type XLIB:FONT-ERROR]
and:
Asynchronous NAME-ERROR in request 38817 (last request was 38818)  Code 45.0 [OpenFont]
   [Condition of type XLIB:NAME-ERROR]

**Comment by gabriel-laddel** [comment]
Could you please supply some details as to the system you're running on (which backend, linux distro, etc).

You may not be aware, but such completions can be canceled with C-c C-c. Screenshot related (note the multiple "Command aborted" strings generated via C-c C-c):  http://imgur.com/1rvk5BR

The font example works for me (screenshot related): http://imgur.com/PfLmqRv

As does the text size test: http://imgur.com/lWza3Ff

I'm using the CLX backend.

**Comment by spaceotter** [comment]
Hi, thanks for your help. I'm using Manjaro linux. I'm not sure which backend because I never specified one, it's probably CLX.

I didn't know the shortcut, I suppose that helps. Cancelling the command is not the same as dismissing the yellow prompt though. If it is sufficiently long the Ok/Cancel buttons are not accessible so I still think this is a bug.

The font selector did work without the truetype extension, but the text size test won't scale without it. There is no error, it just comes up with text the same size. I think some relevant packages may have changed between now and February, as I'm not getting the same errors. There is some problem with the font paths when opening the font selector with truetype, but everything else seems to display fonts anti-aliased which I think is farther than I got in February.

**Comment by gabriel-laddel** [comment]
@spaceotter would you mind marking this closed? Truetype is now the default which should fix your problem.. As for the yellow prompt that won't disappear, the whole of CLIM autocompletion needs to be re-thought out.

**Comment by spaceotter** [comment]
Closed.
