### ISSUE TITLE
union types aren't handled correctly by accepting-values dialog

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#114]
Prompt is "fixed" if we start to type in the field standing for argument having compound type (for instance `(OR NULL STRING)` – clicking on "OK", "Cancel", or other fields doesn't have any effect, so we effectively can't complete the command unless we provide correct value of the first one (that is value which may be accepted as-is).

```
(define-app-command
    (bam :menu t :name "BAM!" :keystroke (#\l :control))
    ((x 'integer)
     (a '(or null symbol))
     (b '(or integer null))))
```

1. If we enter field X – we may type any value (if it's not integer, we'll get accepting-values accept condition) and we can switch field.
2. If we enter field A, we can't leave it unless we type None (first type in compound object).
3. If we enter field B, we can't leave it unless we type integer or none.

Also after trying to press "OK" in 2) or 3), we lose mouse reaction from the `accepting-values` dialog (clicking, hovering etc).

**Comment by gas2serra** [comment]
The problem is in the following presentation method

```
(define-presentation-method accept ((type or)
                                    (stream input-editing-stream)
                                    (view textual-view)
                                    &key)
  (let ((scan-begin (stream-scan-pointer stream)))
    (loop for or-type in types
          do (handler-case (return (accept or-type
                                           :stream stream
                                           :view view
                                           :prompt nil))
               (parse-error () (setf (stream-scan-pointer stream) scan-begin)))
          finally (simple-parse-error "Input type is not one of ~S" types))))
```
