### ISSUE TITLE
Regression in interaction between with-room-for-graphics and draw-circle*

### ISSUE THREAD

**Issue by death** [robert-strandh/McCLIM#1218]
In clim-listener, evaluate the following code:

```
(with-room-for-graphics (*standard-output*)
  (draw-circle* *standard-output* 100 100 50))
```

The circle is not drawn in the right position.
Bisection led me to believe that commit efcfd64 is responsible.

**Comment by dkochmanski** [comment]
Hey, thanks for the report! A band aid fix is to change (inlined!) function to

```
(defun arc-contains-angle-p (start-angle end-angle delta)
  (cond
    ((coordinate= (mod start-angle (* 2 pi))
                  (mod end-angle   (* 2 pi)))
     t)
    ((< start-angle end-angle)
     (coordinate-between* start-angle delta end-angle))
    (t
     (or (coordinate<= start-angle delta)
         (coordinate<= delta end-angle)))))
```

I still want to see why with-room-for-graphics behaves strangely for some inputs (possibly unrelated to the issue at hand) and see whether there is a better fix.
