### ISSUE TITLE
accept doesn't return the original object when it's selected with a pointer

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#132]
What leads to broken commands.

Steps to reproduce – play a bit with this example:
```common-lisp
#-mcclim
(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload 'mcclim))

(defpackage #:bug-clim
  (:use #:clim-lisp #:clim)
  (:export #:gui-main))

(in-package #:bug-clim)

(define-presentation-type foo ())
(define-presentation-type bar ())
(define-presentation-type qux ())
(define-presentation-type ram ())
(define-presentation-type dan ())

(define-presentation-method present
    (object (type foo) stream (view textual-view) &key)
  (format stream "~&#<foo: ~s>" object))

(define-presentation-method present
    (object (type bar) stream (view textual-view) &key)
  (format stream "~&\"bar\"" #+ (or) object))

#+ (or)
(define-presentation-method present
    (object (type qux) stream (view textual-view) &key)
  (format stream "~&\"qux\"" #+ (or) object))

(define-presentation-method present
    (object (type ram) stream (view textual-view) &key)
  (format stream "~&:ram"))

(define-application-frame bug? ()
  ((bar :initform nil :accessor bar)
   (foo :initform nil :accessor foo)
   (qux :initform nil :accessor qux)
   (ram :initform nil :accessor ram))
  (:panes
   (display1 :application :display-function #'show-bug)
   (interactor :interactor))
  (:layouts (default (vertically () display1 interactor))))

(defun show-bug (frame pane)
  (present "bam bam" 'foo)
  (present "bam bam" 'bar)
  (with-output-as-presentation (pane "bam bam" 'qux)
    (format pane "~&:qux"))
  (with-output-as-presentation (pane "bam bam" 'ram)
    (format pane "~&:ram"))
  (format pane "~&current values:
~s [~s]
~s [~s]
~s [~s]
~s [~s]
"
          (foo frame) (type-of (foo frame))
          (bar frame) (type-of (bar frame))
          (qux frame) (type-of (qux frame))
          (ram frame) (type-of (ram frame))))

(define-bug?-command (read-foo :menu t :name "read-foo")
    ((my-foo foo))
  (setf (foo *application-frame*) my-foo))

(define-bug?-command (read-bar :menu t :name "read-bar")
    ((my-bar bar))
  (setf (bar *application-frame*) my-bar))

(define-bug?-command (read-qux :menu t :name "read-qux")
    ((my-qux qux))
  (setf (qux *application-frame*) my-qux))

(define-bug?-command (read-ram :menu t :name "read-ram")
    ((my-ram ram))
  (setf (ram *application-frame*) my-ram))

(defvar *app*)
(defun gui-main ()
  (setf *app* (make-application-frame 'bug?))
  (run-frame-top-level *app*))
```

**Comment by dkochmanski** [comment]
we can't use read-token there, which simply reads strings

**Comment by gas2serra** [comment]
What bug? It seem to me that the result is "correct". Consider that, from clim-ug.pdf:

> "Note that, for a particular view, the present and accept methods must be duals, that is, the
> accept method must be able to parse what the present prints."

When you click on a presentation, I think, it is called "present-to-string" (that call present with textual-view) on that object and that string is pass to accept.
Try `(trace climi::present-to-string)`

**Comment by gas2serra** [comment]
I used a few simple presentation types in the new version of mcclim-desktop and it seem to me that "with-output-as-presentation" is correct.

**Comment by dkochmanski** [comment]
I mean our default methods:
```common-lisp
(define-default-presentation-method present
    (object type stream (view textual-view) &key acceptably for-context-type)
  (declare (ignore for-context-type type))
  (if acceptably
      (let ((*print-readably* t))
        (prin1 object stream))
      (princ object stream)))

(define-default-presentation-method accept
    (type stream view &key default default-type)
  (declare (ignore default default-type))
  (accept-using-read stream type :read-eval t))
```

or (now I see this) wrong fix here:
```common-lisp
(define-default-presentation-method accept
    (type stream view &key default default-type)
  (declare (ignore default default-type))
  (let* ((token (read-token stream)))
    (if (presentation-typep token type)
        (values token type)
        (input-not-of-required-type token type))))
```
which I will revert of course.

In my understanding even if object doesn't have a readable representation it should be possible to select it with a pointer to read it back.

**Comment by gas2serra** [comment]
With textual-view, the object must have an unique textual representation.

> it should be possible to select it with a pointer to use it as input for command.

You can use the option :replace-input

```
(define-bug?-command (read-ram :menu t :name "read-ram")
    ()
  (setf (ram *application-frame*)
	(accept 'ram :replace-input nil)))
```

**Comment by dkochmanski** [comment]
according to `user-ug` (`8.4 Using CLIM presentation types for input`):

> Alternatively, if a presentation of the type specified by the accept call has previously been displayed, the user can click on it with the pointer and accept returns it directly (that is, no parsing is required).

**Comment by dkochmanski** [comment]
Also in the specification (`23.3.1 Defining Presentation Types`):

> Every presentation type must define or inherit presentation methods for accept and present if the type is going to be used for input and output. For presentation types that are only going to be used for input via the pointer, the accept need not be defined.

**Comment by gas2serra** [comment]
> Alternatively, if a presentation of the type specified by the accept call has previously been displayed, the user can click on it with the pointer and accept returns it directly (that is, no parsing is required).

It is the behavior of accept in the listener.

> Every presentation type must define or inherit presentation methods for accept and present if the type is going to be used for input and output. For presentation types that are only going to be used for input via the pointer, the accept need not be defined.

In your example you are asking an input from the keyboard.

**Comment by gas2serra** [comment]
In your example, if you call a command from the interactor using the space (editing in only one line) you have the correct (more correct) behavior. 
I have seen that drei redefine a lot of present/accept staff.

**Comment by dkochmanski** [comment]
What do you mean by

> In your example you are asking an input from the keyboard.

I'm invoking commands from menu and I expect to be able to select arguments with a pointer (and have the object which is presented). How should I define command to ask for an input from the pointer (i.e without interactor etc)?

In my example only the first exampe (which can't be read back due to `#<…>`) returns the original object when I click it, rest is read from its textual representation.

**Comment by gas2serra** [comment]
Insert "read-bar"<space>
> Command: read-bat (bar) 

Clink on a presentation
> Command: read-bat (bar) "bar"

Return

When you invoking commands from menu it is used "dialog.lisp" code. Maybe there is a bug there.

> How should I define command to ask for an input from the pointer (i.e without interactor etc)?

I don't know.

**Comment by gas2serra** [comment]
Read-command call "accepting-values". You can find a descrition in "LispWorks® Common Lisp Interface
Manager User Guide Version 2.0" cap. 12.3 "CLIM Dialog Operators".
It requires that all command arguments have a textual representation.

**Comment by gas2serra** [comment]
In my branch "dialog" you will find an improved version of dialog. I think it is closer to LispWork version of clim and it will solve your problem. I add also some keystroke to avoid using mouse.
