### ISSUE TITLE
presentation-typep: function is too accepting

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#133]
This leads to problems in other parts of code (instead of error, we accept things which we shouldn't):

```common-lisp
> (define-presentation-type bam ())
> (presentation-typep "boo" 'bam) ; => t
```

**Comment by gas2serra** [comment]
The supertype of all other presentation types is T. If you don't define an accept method, I think, it is correct.

**Comment by gas2serra** [comment]
You must define `presentation-typep`. 
```
 (clim:define-presentation-method clim:presentation-typep (object (type bam))
   
)
```

**Comment by dkochmanski** [comment]
You are right, thanks.
