### ISSUE TITLE
enhancement dialog

### ISSUE THREAD

**Issue by gas2serra** [robert-strandh/McCLIM#140]
At the moment accepting-values is only mouse oriented. I would like to use the keyboard to move between fields, to commit and to abort.
My proposal is:

> (#\n :meta) next field
> (#\p :meta) previous field
> (#\] :control) commit accept
> (#\z :control) abort accept

What do you think?

**Comment by dkochmanski** [comment]
I like the idea. `M-n` and `M-p` seem very natural (at least for emacs-oriented users), what about `C-z` and `C-]` though? I would expect abort being `C-g` and commit  being `RET`. Is it some convention I'm not aware of?

Alternatively we may go for `TAB`, `S-TAB` for next/previous and `ESC`, `RET` for cancel/OK (as used in other toolkits.

**Comment by gas2serra** [comment]
C-z and C-] was the keystroke used by LispWorks.
We can't use TAB e RET. TAB is used to complete and RET is used to commit a single field.
C-g is fine.

(#\n :meta) next field
(#\p :meta) previous field
(#] :control) commit accept
(#\g :control) abort accept

**Comment by dkochmanski** [comment]
If it's used in other CLIM implementation, we should follow that I think, so I think now that your original mapping is way better. People who used LW CLIM application won't be suprised.

**Comment by dkochmanski** [comment]
Merged in #141.
