### ISSUE TITLE
clxv3 backend: bug with fonts

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#149]
In clxv3 started as described in https://github.com/robert-strandh/McCLIM/wiki/CLX-backend demo has very big fonts (in fact – unreadable). See attached picture.

![mcc](https://cloud.githubusercontent.com/assets/6871201/24090100/8bb7f5de-0d3d-11e7-8fdf-5c7a2fea46b9.png)

@gas2serra can you take a look at it?

**Comment by gas2serra** [comment]
I did not have this problem. 
I tested it with the master branches of McClim and CLX.
Alessandro

**Comment by gas2serra** [comment]
Do you solve it?
Are you using different branches?
Alessandro

**Comment by dkochmanski** [comment]
sorry for late response – checked right now with fresh `master` branches. It seems I had to have some glitches in cache. Sorry for bothering you – works fine for me.
