### ISSUE TITLE
Improve indentation of documentation strings

### ISSUE THREAD

**Issue by robert-strandh** [robert-strandh/McCLIM#158]
In Core/clim-basic/regions.lisp there are multi-line documentation
strings that have been indented to look good in the source code, but
unfortunately, that means that they will have strange-looking spaces
when they are viewed through CL:DOCUMENTATION.

Use the trick #.(format nil "....") to create the documentation
strings, thereby allowing the use of the ~@ format directive at
the end of lines so that the next line can be indented to look
good in source code, without adding initial whitespace to that
line in the final documentation string.

**Comment by npatrick04** [comment]
FYI, that trick currently breaks McCLIM on Windows with SBCL as the compiler loading of docstrings doesn't handle CRLF correctly.  I've been getting by with fixing those compilation errors each time I hit one.  I haven't had luck tracking down the affecting code in SBCL yet.

https://bugs.launchpad.net/sbcl/+bug/720517

**Comment by dkochmanski** [comment]
as far as I can see it's only `intersection-line/unit-circle` function and `contact-radious*` local function. (both are used only locally and aren't exported). I'll make docstring a comment in the `contact-radious*` and make new lines start in the 0th column in `intersection-line…`.
