### ISSUE TITLE
Decrease line width by introducting a local function

### ISSUE THREAD

**Issue by robert-strandh** [robert-strandh/McCLIM#161]
In the file Core/clim-basic/bezier.lisp, in the method REGION-UNION
(BEZIER-UNION BEZIER-UNION), introduce a local function that takes two
transformations and a region, and that computes:

   (UNTRANSFORM-REGION T1 (TRANSFORM-REGION T2 R)

where T1 and T2 are transformations and R is a region.

Use the new local function to shorten the lines that compute the
:AREAS initialization argument to MAKE-INSTANCE.

Also, in the same function, fix the incorrect indentation of the one
of the instances of teh initialization argument :TRANSFORMATION.

**Comment by dkochmanski** [comment]
@slyrus does this still apply to bezier? if not, we should close this issue.

**Comment by dkochmanski** [comment]
closing, this is more code refactor, and this code to be refactored doesn't exist anymore.
