### ISSUE TITLE
Listener presentation "Menu" windows are created at the wrong size

### ISSUE THREAD

**Issue by abridgewater** [robert-strandh/McCLIM#171]
When opening a context menu on a presentation in the Listener, the window for the menu is created overlarge and then sized down to the required space for the menu, causing a noticeable flicker.

**Comment by gas2serra** [comment]
The problem is in '(defmethod adopt-frame ((fm frame-manager) (frame menu-frame))'. 
The top-sheet is adopted by the graft before calling allocate-space.

**Comment by abridgewater** [comment]
That doesn't quite make sense. The critical bit would be to set the sheet region based on the result of COMPOSE-SPACE before enabling it, which can happen post-graft... Though now I'm having trouble remembering my substructure redirection semantics, so there may be further subtleties here.

**Comment by gas2serra** [comment]
"The critical bit would be to set the sheet region based on the result of COMPOSE-SPACE before enabling it".
I agree. The following method seem to do better. The mirror is created with the wrong size. The size is updated. And, only in the end, the mirror is shown (sheet-enabled-p).
I have a fast PC and I cannot see any difference. Can you test it?

```
(defmethod adopt-frame ((fm frame-manager) (frame menu-frame))
  (setf (slot-value fm 'frames) (cons frame (slot-value fm 'frames)))
  (setf (frame-manager frame) fm)
  (let* ((t-l-s (make-pane-1 fm *application-frame*
                             'menu-unmanaged-top-level-sheet-pane
			     :name 'top-level-sheet
			     :enabled-p nil)))
    (setf (slot-value frame 'top-level-sheet) t-l-s)
    (sheet-adopt-child t-l-s (frame-panes frame))
    (let ((graft (find-graft :port (port fm))))
      (sheet-adopt-child graft t-l-s)
      (setf (graft frame) graft))
    (let ((pre-space (compose-space t-l-s))
          (frame-min-width (slot-value frame 'min-width)))
      (multiple-value-bind (width min-width max-width height min-height max-height)
          (space-requirement-components pre-space)
        (flet ((foomax (x y) (max (or x 1) (or y 1))))
          (let ((space (make-space-requirement :min-width  (foomax frame-min-width min-width)
                                               :width      (foomax frame-min-width width)
                                               :max-width  (foomax frame-min-width max-width)
                                               :min-height min-height
                                               :height     height
                                               :max-height max-height)))
            (allocate-space (frame-panes frame)
                            (space-requirement-width space)
                            (space-requirement-height space))
	    (setf (sheet-region t-l-s)
		  (make-bounding-rectangle 0 0
					   (space-requirement-width space)
					   (space-requirement-height space)))
	    (setf (sheet-transformation t-l-s)
		  (make-translation-transformation (slot-value frame 'left)
						   (slot-value frame 'top)))))))
    (setf (sheet-enabled-p (slot-value frame 'top-level-sheet)) t)))
```

**Comment by abridgewater** [comment]
So, loaded everything, did an (IN-PACKAGE :CLIM-INTERNALS), pasted the replacement method definition, fired up the listener... And it still happens. This very obvious flicker as the X window for the menu is created far too large and then resizes.

**Comment by gas2serra** [comment]
Umm... the content of the menu is created after 'adopt-frame'.

**Comment by gas2serra** [comment]
Hi @abridgewater,
please, can you test #217?

**Comment by abridgewater** [comment]
With #217 applied (the doing of which was non-obvious, no thanks to github) there is no longer any visible indication that the menu windows are created at the wrong size (if, indeed, they still are).

**Comment by gas2serra** [comment]
I'm sorry, I did not know it was difficult to apply a pull request (I never did it).
Thanks!

**Comment by dkochmanski** [comment]
solved in develop branch.
