### ISSUE TITLE
Listener fails to display prompt for non-CLIM interaction code at bottom of window

### ISSUE THREAD

**Issue by abridgewater** [robert-strandh/McCLIM#172]
When using Y-OR-N-P (or, it seems, any other mechanism that prints a prompt, does a FINISH-OUTPUT, and then reads input) at the bottom of the listener window, the prompt does not display until there is subsequent output.
![y-or-n-p at bottom of window](https://cloud.githubusercontent.com/assets/469380/25452346/51f56700-2a93-11e7-9a95-130d3eeb5878.png)

**Comment by dkochmanski** [comment]
fix in master confirmed. closing.
