### ISSUE TITLE
PostScript back end trims top of drawings.

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#190]
The following test:
```
(defpackage #:grid-test
  (:use #:clim #:clim-lisp #:clim-extensions))
(in-package grid-test)
(defun grid-test-1 (&key (file #p"grid-test-1.ps"))
  (format t ";; Creating ~S.~%" file)
  (with-open-file (file-stream file :direction :output :if-exists :supersede)
    (with-output-to-postscript-stream
        (stream file-stream
                :header-comments '(:title "Foo")
                :scale-to-fit t)
      (loop for i from 0 to 100 by 10
         do
           (draw-line* stream i 0 i 100 :line-thickness 2 :ink +black+)
           (draw-line* stream 0 i 100 i :line-thickness 2 :ink +black+))))
  file)

(grid-test-1)
```

yields a PDF with that is only a 5x10 grid. Apparently the top 5 rows are being cutoff. How do we make the page match the drawing?

**Comment by dkochmanski** [comment]
works in master branch now. closing.

**Comment by dkochmanski** [comment]
I've read it wrong (didn't see that it's about PDF).

**Comment by dkochmanski** [comment]
that's what I see:
![obraz](https://user-images.githubusercontent.com/6871201/27046825-2987bf10-4fa6-11e7-931d-0f4de56deba6.png)

**Comment by slyrus** [comment]
Oh, I see what you're saying. The PS file is fine. It's the converted PDF file (from ps2pdf, in this case) that is wrong. perhaps the bug lies elsewhere.

**Comment by slyrus** [comment]
hopefully we won't need ps2pdf much longer.

**Comment by dkochmanski** [comment]
This is probably not McCLIM issue. Also pdf backend is on its way.
