### ISSUE TITLE
undefined function %make-iamge-sheet-get-function called in render/design.lisp

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#199]
It looks like there used to be a function called %make-image-sheet-get-function and that it was removed and uses of it replaced with direct (lambda (x y) ...) calls in the various make-rgba-design methods. The method for image-sheet-mixin still calls this now non-existent function. @gas2serra can you take a look at this?

**Comment by gas2serra** [comment]
Yes, give me a few days.
Alessandro
