### ISSUE TITLE
vertically layout overflow

### ISSUE THREAD

**Issue by gas2serra** [robert-strandh/McCLIM#216]
The 'box-layout-mixin' approximates the required space of its children with 'ceiling'. Sometimes the last child is partially outsize the box.

```
 (defmethod box-layout-mixin/xically-allocate-space-aux* ((box box-layout-mixin) width height)
   (declare (ignorable width height))
   (let ((children (reverse (sheet-enabled-children box))))
     (with-slots (major-spacing) box
       (let* ((content-srs (mapcar #'(lambda (c) (xically-content-sr*** box c major))
                                   (box-layout-mixin-clients box)))
              (allot       (mapcar #'ceiling (mapcar #'space-requirement-major content-srs)))
              (wanted      (reduce #'+ allot))
              (excess      (- major wanted
                              (* (1- (length children)) major-spacing))))
```

**Comment by gas2serra** [comment]
Do we want that the regions of panes are always integer? 
Do we want consider that the pane's regions are always in pixels?

**Comment by gas2serra** [comment]
Hi,
The spec. don't say that the coordinates are integer. 
I try to fix that. It seem to work (only a problem in clim-fix). It is more expensive because the size of the panes is then resized into integer coordinates when the backend send a configuration event.

As RSL said, about graft units,

> Minor issue: I don’t know how much of this is obsolete. — RSL

**Comment by dkochmanski** [comment]
isn't it that we need integer, because after all we are projecting everything to pixels?

**Comment by gas2serra** [comment]
For the drawing function, yes.
For pane size is a bit more complex because the backend send back a configuration event that ask to the pane to change its coordinates.

An example.
If we use real coordinates:

1. pane calls compose-space and allocate-space
2. It asks to the backend to resize a mirror to 100.5 and 100.6.
3. Backend resizes it to 100 and 100.
4. It send back a configuration event for 100 100
5. Pane re-computes its space (because its size is different)
6. It asks to the backend to resize a mirror to 100 and 100 (I think it did it)
7. ...

If we use integer coordinates:

1. pane call allocate-space
2. We ask to the backend to resize a mirror to 100 and 100
3. Backend resizes it to 100 and 100.
4. It send back a configuration event for 100 100

**Comment by gas2serra** [comment]
Moreover,
In clx backend, it happens for every pane.

In clxv3 and clxfb, drawing a rectangle (the background) with integer coordinates is faster than drawing a rectangle with real coordinates.
In the second case, the render uses anti-aliasing.
