### ISSUE TITLE
pixmap drawing tests broken

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#225]
I don't know if 1) this is a regression or 2) the tests should have worked in the first place, but the "Pixmap 1" "Pixmap 2" and "Pixmap 3" tests from the drawing-tests example are now broken and don't display the proper output.

**Comment by gas2serra** [comment]
Hi,
It is a regression.
I changed the "change-space-requirements" policy.
What happens:
1) the Pixmap is drawn into the screen without recording it.
2) the new policy calls change-space-requirements that call repaint
3) the recorded stream repaint all, that is nothing.

**Comment by gas2serra** [comment]
Sorry, I missed to change window-clear method. 

Anyway, if you scroll the stream pane up and down you can see that the Pixmap is not recordered.

**Comment by slyrus** [comment]
Sure, but is that a bug with the tests, or is the new behavior wrong?

**Comment by gas2serra** [comment]
The recording problem is an old bug. Better, it is a missing feature.
There are other methods that are not recorded (you can see them using the recording option).

**Comment by gas2serra** [comment]
The solution that I have proposed is not good. I need to think something better...

**Comment by gas2serra** [comment]
I fix it.

**Comment by dkochmanski** [comment]
Fix merged. Thanks!
