### ISSUE TITLE
LAYOUT-FRAME not called when it should be.

### ISSUE THREAD

**Issue by robert-strandh** [robert-strandh/McCLIM#23]
The specification says that LAYOUT-FRAME should be called when a frame
is adopted.  But this does not seem to be the case.  Instead, frame
adoption does something equivalent to what LAYOUT-FRAME does, but
without calling LAYOUT-FRAME.

As it turns out, LAYOUT-FRAME does (or did?) not work properly.  It is
called from (SETF FRAME-LAYOUT), and because it did not work, changing
the layout of a frame also did not work.

In investigating why changing the frame layout did not work, I noticed
that an :AROUND method on ALLOCATE-SPACE skips the primary method if
the top-level sheet has the same size as the previous time.  The
reason for skipping the primary method is probably an attempt to
optimize.  But when the layout has changed, even though the top-level
sheet has the same size, skipping the primary method is not the right
thing to do.

For now, I removed the size test so that the primary method is always
run.  However, I also noticed that there seem to be WAY too many calls
to COMPOSE-SPACE and ALLOCATE-SPACE.  I still don't know why, but I
will continue investigating this problem as part of my general
maintenance effort.

**Comment by gabriel-laddel** [comment]
In the spirit of staying on topic - do you, or anyone else have a reason to keep around goatee?

**Comment by robert-strandh** [comment]
Not really, no.  I was going to replace the buffer code by the new
library I wrote (Cluffer) just to see how much would be left of Goatee
itself, but I don't know whether I will get around to doing that.

**Comment by gabriel-laddel** [comment]
Would you mind describing why Cluffer is better than drei-buffer?

**Comment by robert-strandh** [comment]
The buffer of Drei comes from Climacs.  It is represented as a single
gap buffer.  That representation makes many things hard.  In
particular, adding things like state of an incremental parser requires
the use of a lot of cursors, which slows things down and makes it
basically equivalent to having explicit representations for lines.

The other problem with a single gap buffer is that it is hard to
design an update protocol, i.e., a way for views to find out what has
changed since the last update.

For more details, I refer you to the paper I submitted to ELS2016 (and
which we will soon know whether it is accepted):

    http://metamodular.com/cluffer.pdf

The reason for wanting to replace the buffer of Drei, Climacs, and
Goatee with Cluffer has more to do with cutting down on the amount of
code that needs to be maintained by using the same library in several
editors.  I am more nervous about replacing the buffer of Drei/Climacs
than of Goatee because Drei is used as the default input editor of
McCLIM.

**Comment by dkochmanski** [comment]
The following example works OK for me:
```common-lisp
(eval-when (:compile-toplevel :load-toplevel :execute)
  (ql:quickload 'mcclim))

(defpackage #:mcclim/bug/change-layout
  (:use :clim :clim-lisp)
  (:export #:app-main))

(in-package #:mcclim/bug/change-layout)

(define-application-frame buggyapp ()
  ()
  (:panes (int :interactor)
          (app :application))
  (:layouts
   (:default int app)
   (:inverse app int)))

(defun app-main ()
  (run-frame-top-level (make-application-frame 'buggyapp)))

(define-buggyapp-command (switch-layout :name t) ((layout 'symbol))
  (setf (frame-current-layout *application-frame*) layout))
```
