### ISSUE TITLE
When using incremental-redisplay, the size of the pane doesn't change when the content changes

### ISSUE THREAD

**Issue by lokedhs** [robert-strandh/McCLIM#251]
To reproduce this problem, run the test case below. Issue the command `Rows` and type a number that causes the pane to display more content than fits in the window, for example 100.

Then, type the same command again, but choose a smaller number. Notice how the size of the pane does not change and you can scroll into a large blank area below.

Another problem which this test program does not reproduce is that if you use `UPDATING-OUTPUT` and an output record changes such that its vertical dimension becomes larger, the pane will also not accommodate and in this case the problem is that some content at the end of the pane will now be hidden.

```
(clim:define-application-frame resize-test-frame ()
  ((rows :initform 0
         :accessor resize-test-frame/rows))
  (:panes (content :application
                   :display-function 'display-content
                   :display-time t
                   :incremental-redisplay t)
          (interaction-pane :interactor))
  (:layouts (default content
                     interaction-pane)))

(defun display-content (frame stream)
  (loop
    for i from 0 below (resize-test-frame/rows frame)
    do (format stream "Row number: ~a~%" i)))

(defun open-resize-test-frame ()
  (let ((frame (clim:make-application-frame 'resize-test-frame)))
    (clim:run-frame-top-level frame)))

(define-resize-test-frame-command (rows :name "Rows")
    ((n 'integer))
  (let ((frame clim:*application-frame*))
    (setf (resize-test-frame/rows frame) n)
    (setf (clim:pane-needs-redisplay (clim:find-pane-named frame 'content)) t)))
```

**Comment by gas2serra** [comment]
I think it is not a bug. 
The height of a stream-pane grows automatically but never shrink automatically. 
If you want you can use ':compute' value for ':width' and ':height'. 

`(content :application
                   :display-function 'display-content
                   :display-time t
                   :incremental-redisplay t
                   :width :compute
                   :height :compute)`

**Comment by gas2serra** [comment]
There is a little bug: you cannot use only ':height :compute'... I'm fixing it.

**Comment by lokedhs** [comment]
@gas2serra Thank you. That worked a bit better. However, the scrollbar gets a repaint problem which is fixed as soon as I resize the window. Do you see that too?

**Comment by gas2serra** [comment]
I'm going to fix it.

**Comment by gas2serra** [comment]
Fixed.
