### ISSUE TITLE
BOUNDING-RECTANGLE-WIDTH does not take the scrollbars into account

### ISSUE THREAD

**Issue by lokedhs** [robert-strandh/McCLIM#254]
When using BOUNDING-RECTANGLE-WIDTH to determine the width of a pane which as vertical scrollbars enabled, the result includes the width of the scrollbars. This means that any application that wants to draw something that fills the entire width of the pane will draw outside the visible area (in other words: it will end up trying to draw on top of the scroll bars).

**Comment by gas2serra** [comment]
To get only the visible area you can use '(clim:pane-viewport-region stream)'.

**Comment by dkochmanski** [comment]
it is a correct behavior needed to determine pane width - scroll bars are part of width. As mentioned, pane-viewport-region is a way to go.
