### ISSUE TITLE
keystroke accelerators with :super modifier don't work

### ISSUE THREAD

**Issue by admich** [robert-strandh/McCLIM#293]
In clx backend defined keystroke accelerators with :super modifier don't work.
I think this is due to a typo error in file:
[McCLIM/Backends/CLX/keysyms-common.lisp](https://github.com/robert-strandh/McCLIM/blob/master/Backends/CLX/keysyms-common.lisp)

In line 177 the \*super-bit\* is defined #b00100000 as \*hyper-bit\* corresponding to mod3 instead of mod4 of X server.

If you change line 177 with:
```common-lisp
(defparameter *super-bit*     #b01000000)
```
the keystroke accelerators with :super start to work

**Comment by dkochmanski** [comment]
Incorporated, thanks!
