### ISSUE TITLE
How to use COMPOSE-IN transparency within presentations?

### ISSUE THREAD

**Issue by scymtym** [robert-strandh/McCLIM#298]
Using transparency like ``:background (clim:compose-in clim:+blue+ (clim:make-opacity .1))`` while outputting a presentation leads to visual artifacts (see https://techfak.de/~jmoringe/compose-in-ink.ogv) when the created output-records are redisplayed, for example due to scrolling. The following code demonstrates the problem:

```cl
(cl:in-package #:cl-user)

(clim:define-application-frame compose-in-test ()
  ()
  (:panes
   (render :application
           :width 600 :height 400
           :display-function 'render))
  (:layouts
   (default render)))

(clim:define-presentation-type ast-node ())

(defun render (frame pane)
  (clim:with-output-as-presentation (pane nil 'ast-node)
    (clim:surrounding-output-with-border
        (pane :padding 0 :filled t :background (clim:compose-in clim:+blue+ (clim:make-opacity .1)))
      (write-string (documentation 'trace 'function) pane)
      (clim:with-output-as-presentation (pane nil 'ast-node)
        (clim:surrounding-output-with-border
            (pane :padding 0 :filled t :background (clim:compose-in clim:+green+ (clim:make-opacity .1)))
          (write-string (documentation 'break 'function) pane))))))

(clim:run-frame-top-level (clim:make-application-frame 'compose-in-test))
```

**Comment by nsrahmad** [comment]
There is nothing wrong with above code. This seems to be a bug in current standard backend. It works (very slow) on frame-buffer backend without any problem.
P.S. see https://github.com/robert-strandh/McCLIM/wiki/CLX-backend(s) for how to switch to frame-buffer backend.

**Comment by scymtym** [comment]
> There is nothing wrong with above code. This seems to be a bug in current standard backend.

Thanks for having a look.

> It works (very slow) on frame-buffer backend without any problem. P.S. see https://github.com/robert-strandh/McCLIM/wiki/CLX-backend(s) for how to switch to frame-buffer backend.

I can confirm that. The original code which I used to record the linked video also works as expected with the frame-buffer backend.
