### ISSUE TITLE
some define-command forms now fail to compile

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#300]
The problem shows its head in Apps/Listener/dev-commands.lisp in the (define-command (com-run ...) ...) form.

The problem is that we switched from using climi:parse-lambda-list to alexandria:parse-ordinary-lambda list in define-command and this fails for some of the lambda lists we use in clim (particularly in the listener and in scigraph).

We can:

1) revert to climi:parse-lambda-list

2) "fix" alexandria's

or 3) figure out why the lambda lists aren't working with alexandria and see if there is a legitimate bug.

**Comment by dkochmanski** [comment]
this is fixed in develop branch afair.
