### ISSUE TITLE
accepting-values: on `end' choice should return value of last form in body

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#308]
Steps to reproduce:
1.  `(clim-listener:run-listener)`
2.  `(accepting-values (t) (accept 'string) 4)`

Expected: returns 4 when `OK` selected
Observed: returns `NIL`

Other "issue" is that not having `accept` in accepting-values puts us in the debugger. this cuold be no-op which expands to `(progn ,@body)` if no accept clauses are present or a window / dialog without innputs , but with OK/Cancel buttons.

Steps to reproduce:

1.  `(clim-listener:run-listener)`
2.  `(accepting-values (t) 4)`

Expected: returns 4 immedietly (or when `OK` selected- something to be discussed)
Observed: debugger complaining about no accept inside

http://bauhh.dyndns.org:8000/clim-spec/26.html#_1364

>  Builds a dialog for user interaction based on calls to accept within body. The user can select the values and change them, or use defaults if they are supplied. The dialog will also contain some sort of "end" and "abort" choices. If "end" is selected, then accepting-values returns whatever values the body returns. If "abort" is selected, accepting-values will invoke the abort restart. [annotate]

**Comment by dkochmanski** [comment]
```
16:10 < jackdaniel> nyef: what do you think about remark regarding expanding to progn when tehre is no accept forms?
16:59 < nyef> That seems wrong. What if you just want a label and the exit boxes?
17:02 < jackdaniel> but it shouldn't error
17:02 < jackdaniel> so just a box with no inputs
17:13 < nyef> Well, it'd have the exit boxes, but no ACCEPT type inputs.
17:14 < nyef> A simple example would be a JavaScript "alert()" box.
17:15 < nyef> I'd also expect that if OWN-WINDOW is set then the new toplevel window would have WM_TRANSIENT_FOR or similar, and that something semi-sane would happen in 
              terms of event handling, at least for repaint.
```

**Comment by nsrahmad** [comment]
As for other issue (enter debugger when not provided `accept`),
thats actually the ideal behavior. Note the first sentence in [spec](http://bauhh.dyndns.org:8000/clim-spec/26.html#_1364):
> Builds a dialog for user interaction based on calls to accept within body

and in third paragraph

> body is the body of the dialog, which contains calls to accept that will be intercepted by accepting-values and used to build up the dialog.

This actually implies user **must** call `accept` within the `accepting-values`, maybe we need to add the clarification to spec or the manual to explicitly mention it.

The whole point of `accepting-values` is to call `accept` and get input. If you just want to show a `alert()` box, [**`notify-user`**](http://bauhh.dyndns.org:8000/clim-spec/28-3.html#_1521) is much more suitable for it.

**Comment by dkochmanski** [comment]
OK, thanks for analyzing this. In that case we should have a clear error message, like:
`you must include accept clause in accepting-values` instead of cryptic:

```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::QUERY-IDENTIFIER (2)>
when called with arguments
  (NIL).
   [Condition of type SIMPLE-ERROR]
```

and I see `[OK] [Cancel]` buttons in the listener when I'm in the debugger. That should fail before doing any drawing with intelligible message, that accept clauses must be inside accepting-values.
