### ISSUE TITLE
Slider class from 30.4.5 is missing

### ISSUE THREAD

**Issue by npatrick04** [robert-strandh/McCLIM#311]
I implemented a simple dial and clock gadget at https://github.com/npatrick04/clim-dial.  I tried implementing it directly from the spec, and found that the slider class from 30.5.4 of the spec was named slider-gadget.  

I updated the slider gadget code at npatrick04/McCLIM@8cc6340eef1f5581e34cbdfaf3572b372236937b.  So if it's agreeable, I'll submit a pull request.

**Comment by dkochmanski** [comment]
closing since your PR fixed that. Thank you for waiting (I'll try to improve my response time).
