### ISSUE TITLE
[$100] Text field pane height is too small, clipping the bottom off characters

### ISSUE THREAD

**Issue by john-a-carroll** [robert-strandh/McCLIM#317]
This example shows the problem:

```
(define-application-frame text-field-frame ()
  ()
  (:pane
    (spacing (:thickness 40)
      (horizontally (:x-spacing 10)
         (make-pane 'label-pane :label "abc_def")
         (make-pane 'text-field :value "ghi_jkl" :width 250)))))

(run-frame-top-level (make-application-frame 'text-field-frame))

```
The label pane displays abc_def correctly, but the underscore character in ghi_jkl is not visible in the text field pane.

Text field height was correct in mcclim-20160929. Since then there have been changes to `box-layout-mixin/xically-allocate-space-aux*` to remove calls to `ceiling`. If I put those calls back in then this text field height problem is fixed. Could those changes be reverted?

**Comment by dkochmanski** [comment]
@gas2serra this is a commit: 454f659c0e776ecc68e9d6ce78bd450f2f0c3ddd , do you think we could revert it? I don't know how it will affect framebuffer backend.

**Comment by gas2serra** [comment]
Hi,
I'm going to test it and find a solution.

**Comment by john-a-carroll** [comment]
Thanks for looking into this. Could you also try the test case below, which adds a spacing pane around the text field? Even if I revert `box-layout-mixin/xically-allocate-space-aux*` and `stack-space-requirements-xically`, the underscore in the text field is invisible. So perhaps there's something else involved here.

```
(define-application-frame text-field-frame ()
  ()
  (:pane
    (spacing (:thickness 40)
      (horizontally (:x-spacing 10)
         (make-pane 'label-pane :label "abc_def")
         (spacing (:thickness 3 :background +white+)
           (make-pane 'text-field :value "ghi_jkl" :width 250))))))

(run-frame-top-level (make-application-frame 'text-field-frame))
```

For the moment I hack around this in my application, by adding a thin space immediately below the text field, which for some reason allows the underscore to show up:

```
(define-application-frame text-field-frame-hack ()
  ()
  (:pane
    (spacing (:thickness 40)
      (horizontally (:x-spacing 10)
         (make-pane 'label-pane :label "abc_def")
         (spacing (:thickness 3 :background +white+)
           (vertically (:background +white+)
             (make-pane 'text-field :value "ghi_jkl" :width 250)
             1))))))

(run-frame-top-level (make-application-frame 'text-field-frame-hack))
```

**Comment by gas2serra** [comment]
I think that the difference is that text fields and label panes allocate a different height.
In the following example, the height of the label is 17 while the height of the text is 13.
```
(define-application-frame text-field-frame ()
  ()
  (:panes
   (label (make-pane 'label-pane :label "abc_def"))
   (text (make-pane 'text-field :value "ghi_jkl" :width 250))
   (test (make-pane 'push-button :label "test" :activate-callback
                    #'(lambda (x)
                        (format *debug-io* "~A~%" (sheet-region
                                                   (clim:find-pane-named *application-frame*
                                                                         'label)))
                        (format *debug-io* "~A~%" (sheet-region
                                                   (clim:find-pane-named *application-frame*
                                                                         'text)))))))
  (:layouts
   (default 
       (spacing (:thickness 40)
         (horizontally (:x-spacing 10)
           (spacing (:thickness 3 :background +red+)
             label)
           (spacing (:thickness 3 :background +yellow+)
             text)
           test)))))
```

**Comment by gas2serra** [comment]
reverting to commit: 454f659c0e776ecc68e9d6ce78bd450f2f0c3ddd the heights were: 17.9 and 13.9...

**Comment by nsrahmad** [comment]
Hello everyone,

Problem seems to be in `compose-space` where `height` of the `text-field` is calculated by adding `ascent` and `descent` part of the text. By adding `stream-vertical-spacing` of the pane to `height`, It behaves normally.

Code I will be using to test:
```lisp
(in-package :clim-user)

(define-application-frame text-field-frame ()
  ()
  (:panes
   (text1 (make-pane 'text-field :value "ghi_jkl" :width 250 :text-style (make-text-style :sans-serif nil :small)))
   (text2 (make-pane 'text-field :value "ghi_jkl" :width 250 :text-style (make-text-style :sans-serif nil :normal)))
   (text3 (make-pane 'text-field :value "ghi_jkl" :width 250 :text-style (make-text-style :sans-serif nil :large)))
   (text4 (make-pane 'text-field :value "ghi_jkl" :width 250 :text-style (make-text-style :sans-serif nil :huge))))
  (:layouts
   (default 
       (spacing (:thickness 40)
         (vertically (:y-spacing 8)
           text1
	   text2
	   text3
	   text4)))))

(defun main ()
  (let ((frame (make-application-frame 'text-field-frame)))
    (clim-sys:make-process (lambda () (run-frame-top-level frame)))
    frame))
```


![before](https://user-images.githubusercontent.com/10996250/31994719-4f52b322-b99f-11e7-9c4b-09b722a1998f.png) ![magnified](https://user-images.githubusercontent.com/10996250/31994756-700c5cee-b99f-11e7-97ff-c0b056da9aea.png)

With above mentioned change,

![after](https://user-images.githubusercontent.com/10996250/31994827-b17ade1c-b99f-11e7-8164-6db7c67ba5c4.png) ![after-mag](https://user-images.githubusercontent.com/10996250/31995075-9eb86bf4-b9a0-11e7-9da3-3115b3e8e0f9.png)
