### ISSUE TITLE
Pane scrolls on each key press in input-promt

### ISSUE THREAD

**Issue by knobo** [robert-strandh/McCLIM#32]
Using the lisp-listener, I select the Display Image command, and write the path to a file in the input-prompt. On every keypress the Pane scrolls down until the input field is not visible.
Only the label for the input-prompt is visible.

As in the image attached
![screenshot from 2016-06-07 20-24-47](https://cloud.githubusercontent.com/assets/89921/15869732/f8a31c72-2ced-11e6-9fc5-c03a4a4734da.png)

**Comment by dkochmanski** [comment]
This problem is caused by a `pointer-documentation` set to true in the application frame. This is a bug with calculating the viewport size I suppose (didn't investigate it yet).

**Comment by dkochmanski** [comment]
Spurious values are produced in method allocate-space specialized on `viewport-pane`:

`(gadget-value vscrollbar)` produces rational number on each key-press which gets propagated via `move-and-resize-sheet` to `move-sheet` which makes things scroll in a "wrong way".

I'm leaving this issue for now, because I'm evidently stuck. When I'll learn McCLIM design better I'll try to fix it again. Temporal solution: not using `pointer-documentation`.

**Comment by gabriel-laddel** [comment]
Patch the CLIMI::SCROLLER-PANE defclass to solve the miscalculation in CLIMI::SCROLLER-PANE/UPDATE-SCROLL-BARS which does not take into account PANE-X-SPACING or PANE-Y-SPACING:

```
(defclass scroller-pane (composite-pane)
  ((scroll-bar :type scroll-bar-spec ; (member t :vertical :horizontal nil)
               ;; ### Note: I added NIL here, so that the application
               ;; programmer can switch off scroll bars alltogether. 
               ;; The spec though has it neither in the description of
               ;; SCROLLER-PANE, nor in the description of
               ;; MAKE-CLIM-STREAM-PANE, but in OPEN-WINDOW-STREAM.
               ;;
               ;; One might argue that in case of no scroll-bars the
               ;; application programmer can just skip the scroller
               ;; pane altogether. Bu I think that the then needed
               ;; special casing on having a scroller pane or a bare
               ;; viewport at hand is an extra burden, that can be
               ;; avoided.
               ;; --GB 2005-11-29
               :initform t
               :initarg :scroll-bar
               :accessor scroller-pane-scroll-bar)
   (viewport   :initform nil)
   (vscrollbar :initform nil)
   (hscrollbar :initform nil)
   (suggested-width  :initform 300 :initarg :suggested-width)
   (suggested-height :initform 300 :initarg :suggested-height)
   (vertical-scroll-bar-position
    :initform clim-extensions:*default-vertical-scroll-bar-position*
    :initarg :vertical-scroll-bar-position
    :type (member :left :right)
    :documentation "Whether to put the vertical scroll bar on the left hand or
                    right hand side of the scroller pane."))
```
  (:default-initargs
   :x-spacing 0
   :y-spacing 0))

**Comment by gabriel-laddel** [comment]
Oh, if someone wants to close the issue, would be great...

**Comment by knobo** [comment]
Works for me.
