### ISSUE TITLE
Improvements to format-graph-from-roots - :maximise-generations, :center-nodes, digraphs

### ISSUE THREAD

**Issue by john-a-carroll** [robert-strandh/McCLIM#321]
When a DAG is representing a hierarchy (e.g. a hierarchy of classes or types), one normally expects subtype links to go from left to right. But this is not normally guaranteed by `format-graph-from-roots` with `:graph-type :dag`. For instance, if we graph the subclasses of clim:gadget, once should expect menu-button-pane to be to the right of its superclass menu-button, but in fact menu-button-pane could be placed in the same 'generation' or even to the left of menu-button since it has a further, higher level, supertype standard-gadget-pane. In such cases, we need the `:maximise-generations` keyword implemented in Franz Allegro CLIM (see https://franz.com/support/documentation/6.0/doc/clim-ug.pdf), which ensures that all subtype relationships clearly go left to right. I have implemented this - in fact it's vital for my current McCLIM application.

While I was looking at the code, I noticed that `:center-nodes` was not implemented, so I added it. (With this option, each node of the graph is centered with respect to the widest node in the same generation).

I also decided to get `:graph-type :digraph` working properly (there was some support for it, but it gave errors). I also made the output clearer in the case of an arc from a node back to itself.

I reorganised the code for `layout-graph-nodes` to remove duplicated code between tree and DAG layout, commented some non-obvious bits of code, and added a couple more tests.

I append a screenshot showing some of these new features on the example graphs at
http://www.paoloamoroso.it/log/040819.html
http://www.greatandlittle.com/studios/index.php?post/2013/02/19/Collections-in-Dart-The-Directed-Graph

Although it's quite a big revision, I think it's a significant improvement. I'm happy to prepare a PR.

![format-graph-from-roots](https://user-images.githubusercontent.com/31476017/30066480-ee5306f6-924f-11e7-8b02-0aded0530465.png)

**Comment by dkochmanski** [comment]
Sounds very good to me, please prepare the PR. Thank you!

If I may ask – what application are you working on?

**Comment by john-a-carroll** [comment]
The application is the LKB System, a natural language grammar development environment. See http://moin.delph-in.net/LkbTop, and for my current work on it http://moin.delph-in.net/LkbMacintosh.
