### ISSUE TITLE
render backend broken with new SBCLs

### ISSUE THREAD

**Issue by slyrus** [robert-strandh/McCLIM#331]
The following commit:

https://github.com/sbcl/sbcl/commit/13093605065ba519456efc2c1effb2a5be787122

broke the drawing stuff in the render backend.

To reproduce use any SBCL build following that (.e.g. today's HEAD) and run the drawing-tests. All (?) of the drawing tests give a type error along the lines of -229 is not an unsigned byte 8.

If you set *break-on-signals* t and run the test, you end up in one of the image drawing functions defined in opticl-image.lisp, e.g. def-fast-image-with-stencil.

Unfortunately, this is all a twisty maze of metaprogramming, methods, etc... that is a pain to debug.

In any event, the SBCL commit in question tightened the type restrictions for arguments to foreign lambdas. It's not clear to me if we're (eventually) getting to some FFI code down here, or if those type restrictions are causing new problems for lisp-only code, but it does appear that the render backend is doing something wrong here.

**Comment by slyrus** [comment]
@gas2serra the problem seems to be that a call to lerp such as:

(MCCLIM-RENDER-INTERNALS::%LERP 229 0 200)

turns around and calls 

(MCCLIM-RENDER-EXTENSIONS:OCTET-MULT 200 -229)

but octet-mult is declaimed to only take octets. Either we need to pass it only octets, or fix the declamation.

**Comment by dkochmanski** [comment]
fixed with #332
