### ISSUE TITLE
CLX-fb: rotated ellipses: angles are distorted

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#348]
When we draw rotated ellipse rotated by angle theta, if theta is not ortogonal, angle distance is not preserved. Don't know how to fix that, probably distorted by bezier approximation. See Extensions/renderer/mediumllisp medium-draw-ellipse* for the code.

Steps to reproduce: run `ellipse angle transformations` test.

**Comment by dkochmanski** [comment]
![xxx](https://user-images.githubusercontent.com/6871201/32407102-25a3238a-c184-11e7-81af-fac9f975738a.png)

**Comment by gas2serra** [comment]
Hi Daniel,
Sorry, I did not find the test: _run ellipse angle transformations_.

**Comment by dkochmanski** [comment]
Hey, sorry for not being specific enough. This test is added in this (not merged yet) pull request: https://github.com/robert-strandh/McCLIM/pull/347 , before it none of backends could render rotated ellipsis.

**Comment by dkochmanski** [comment]
fixed by contribution from @mgi
