### ISSUE TITLE
[launchpad #525379]  stream-pointer-position returns incorrect pointer position for the scrolled sheets 

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#370]
https://bugs.launchpad.net/mcclim/+bug/525379

When the sheet-transformation of sheet is changed, the sheet-native-transformation is not updated for mirrored-sheet-mixins. As a result, the stream-pointer-position returns incorrect pointer position on scrolled sheet which is calculated using the sheet-native-transformation. I think this is because (setf native-transformation nil) is commented in (defmethod invalidate-cached-transformations ((sheet mirrored-sheet-mixin)) with strange description "XXX hm...". The method (defmethod sheet-native-transformation ((sheet mirrored-sheet-mixin)) does nothing if native-transformation has not been invalidated. These methods are defined in sheets.lisp

In attached example I create the pane 'canvas' with :min-height 2000 :min-width 2000 and layout (scrolling (:height 500 :width 500) ...). In define-presentation-action for blank-area I call stream-pointer-position and print string "TEST" at this point. In Allegro's CLIM implementation the strings appear where I have pressed pointer button; in McCLIM they appear only at the first page of canvas, even if I have pressed button on blank-area on the other pages.

```
(defpackage :stream-pointer-position-bug
  (:use :clim-lisp :clim))

(in-package :stream-pointer-position-bug)

(defun run ()
  (run-frame-top-level (make-application-frame 'main)))

(define-application-frame main ()
  ()
  (:menu-bar nil)
  (:panes
   (canvas (scrolling (:height 500 :width 500) 
	     (make-pane 'application-pane
			:display-time nil 
			:background +black+ :foreground +white+
			:min-width 2000 :min-height 2000
			:scroll-bars t
			:display-function #'draw-circle
			:name 'canvas
			:output-record (make-instance 
					'standard-tree-output-history)))))
   (:layouts
    (:main canvas)))

(defun draw-circle (frame pane)
  (declare (ignore frame))
  (draw-circle* pane 1500 1500 70 :filled t :ink +yellow+))

(define-presentation-action test
    (blank-area nil main :gesture :select)
    (presentation window)
  (declare (ignore presentation))
  (multiple-value-bind (x y)
      (stream-pointer-position window)
    (draw-text* window "TEST" x y)))
```

**Comment by nsrahmad** [comment]
Fixed in `improve-user-experience` branch.
