### ISSUE TITLE
Typing beyond the right edge of the Listener stream pane after it is vertically full causes the viewport to scroll all the way to the left

### ISSUE THREAD

**Issue by abridgewater** [robert-strandh/McCLIM#390]
Steps to reproduce:
1. Open a fresh Listener.
2. Generate enough output to cause vertical scrolling (`,Show Directory /usr/lib/` should do the trick).
3. Start entering a long Lisp form on one line, to the point where it goes past the right edge of the window. Note that the window remains at the leftmost scroll position, and snaps back there when entering more characters even after scrolling to the right.

**Comment by dkochmanski** [comment]
another way to reproduce this error is to run `clim-fig`.

1. draw a line which extends sheet right and down
2. scroll somewhere in the middle of the sheet
3. draw anything that fits in the viewport

Expected: line is drawn and scrolling is unaffected.
Observed: line is drawn and viewport is scrolled to the left and to the bottom.
