### ISSUE TITLE
Inspector: overlapping output

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#408]
When using image viewer demo, when I select `display image` in the menu, I see overlapping output:

![obraz](https://user-images.githubusercontent.com/6871201/33242507-70be868a-d2d6-11e7-895a-57e182b3c049.png)

**Comment by nsrahmad** [comment]
Hello @dkochmanski ,
b54eac6b introduces this. Since this looks like a branch disguised as a commit, you might have better luck correcting it.
