### ISSUE TITLE
scrolling : events in text-entry gadget affects other panes too

### ISSUE THREAD

**Issue by nsrahmad** [robert-strandh/McCLIM#413]
This bug is present in `improve-user-experience` branch.

steps to reproduce
1) Run `List Test` demo in `demodemo`.
2) Select some random items to fill the interactor-pane.
3) Scroll `matching-symbols` pane to the bottom.
4) Now with every mouse click or keystroke events in text-entry gadget, Both above and below panes scroll up a little. Both panes seem to stop scrolling up after one-viewport-worth of space.

**Comment by dkochmanski** [comment]
this problem is not a regression (present also on master branch)

**Comment by nsrahmad** [comment]
Fixed with https://github.com/robert-strandh/McCLIM/pull/411/commits/a9d53a2300326373a93d0dbcf5881a2b508ee5b9
