### ISSUE TITLE
scrolling : scrollbars doesn't reset or shrink back

### ISSUE THREAD

**Issue by nsrahmad** [robert-strandh/McCLIM#414]
Steps to reproduce
1) Run `List Test` in `demodemo`.
2) Type `CLIM` in text-entry gadget and press `update`. There will be only four elements in in the list but notice the scroll bars doesn't shrink. it did grow if you type `PRESENT`,

Also if you have scrolled enough before entring `CLIM`, Scroll bars won't reset to the top.

**Comment by dkochmanski** [comment]
this is list-gadget issue (not scrolling itself)
