### ISSUE TITLE
Listener: the prompt text is drawn over the input field

### ISSUE THREAD

**Issue by wmannis** [robert-strandh/McCLIM#425]
This is with SBCL on macOS High Sierra, current quicklisp libraries for everything.

<img width="442" alt="clim-font" src="https://user-images.githubusercontent.com/11655511/34801543-e9428126-f62e-11e7-9576-9562747f7c30.png">

**Comment by nsrahmad** [comment]
Thanks for reporting!
This is already fixed in the master branch (See #408).

**Comment by wmannis** [comment]
Ah! My search strings failed me. Sorry for the bother.
