### ISSUE TITLE
ACCEPTING-VALUES :OWN-WINDOW T ignoring :HEIGHT and :WIDTH

### ISSUE THREAD

**Issue by wmannis** [robert-strandh/McCLIM#430]
When `accepting-values` gets `:own-window t` the window is supposed to use `:width` and `:height` if they're given (http://bauhh.dyndns.org:8000/clim-spec/26.html#_1364). They appear to be ignored currently.

**Comment by nsrahmad** [comment]
Hello @wmannis , Thanks for reporting this bug.

when we call `accepting-values` with `:own-window t`, it wraps the local function —which does the real work— with `with-stream-in-own-window`. All we need to do is pass :width and :height to `with-stream-in-own-window` and modify `with-stream-in-own-window` to accept keyword arguments :width and :height.

**Comment by nsrahmad** [comment]
fixed with b6b87fc9dd077
