### ISSUE TITLE
text input fields don't inherit color of pane (except behind text)

### ISSUE THREAD

**Issue by wmannis** [robert-strandh/McCLIM#444]
I'm setting up an app with a solarized color theme. The interactor paints as expected until you try a command that requests information:

<img width="390" alt="drei-background" src="https://user-images.githubusercontent.com/11655511/36677970-2875c770-1ad5-11e8-88e6-3bca4896963b.png">

Is there a way to make the text input fields either inherit the color from the containing pane completely, or to keep its own colors completely, instead of this curious mix?

**Comment by nsrahmad** [comment]
Hello @wmannis , 89acb5a should fix it. Can you confirm it? (change is simple enough to make locally).

**Comment by wmannis** [comment]
That fixes it.

**Comment by nsrahmad** [comment]
Cool, Thanks for reporting.
