### ISSUE TITLE
can't make push-buttons outside of define-application-frame

### ISSUE THREAD

**Issue by Reepca** [robert-strandh/McCLIM#48]
```
; works

(define-application-frame superapp ()
  ()
  (:pane
   (make-pane 'push-button)))

(defun app-main ()
  (let ((application-frame (make-application-frame 'superapp)))
    ;(make-pane 'push-button :label "hi" :client application-frame :id 'test) <--- doesn't work
    (run-frame-top-level application-frame)))
```

In that example, the error is:

> There is no applicable method for the generic function
  #\<STANDARD-GENERIC-FUNCTION CLIM:MAKE-PANE-1 (17)\>
when called with arguments
  (NIL NIL PUSH-BUTTON :LABEL "hi" :CLIENT
   #\<SUPERAPP {10060A71D3}\> :ID TEST).
   [Condition of type SIMPLE-ERROR]

I assume it's supposed to work because the spec (or at least, the one in Documentation/Specification/) has an example on page 321 in which they try something similar.

Using SBCL 1.3.1 on Ubuntu 16.04 with MCCLIM 0.9.7-dev (I know because ASDF complains about it being an invalid version specifier when it loads it, but hey, it's what's in quicklisp)

Hope that's useful.

**Comment by gabriel-laddel** [comment]
Am away from teh repl, but if you invoke that inside of CLIMI::WITH-LOOK-AND-FEEL-REALIZATION it should produce the button

**Comment by gabriel-laddel** [comment]
["this sounds like a stupid question even to me... but how does one make a push-button be a certain size? The examples I've looked at seem to just let it be whatever size the text is."
](http://irclog.tymoon.eu/freenode/%23clim?around=2016-07-09T12:00:15&types=mnaot#1468065615)

The compose-space/allocate-space logic needs to be written downsomewhere in a readily comprehensible manner (there is a start, 118 of /Core/clim-core/panes.lisp), but until then...

```
(in-package climi)

(define-application-frame happy-grandparents () ()
  (:panes (start-recording :push-button
                           :label "Start Recording")
          (stop-recording :push-button
                          :label "Stop Recording"))
  (:layouts (:default (horizontally ()
                        ; this 400 is necessary for whatever reason..
                        (400 (vertically ()                               
                               (100 start-recording)
                               200 ; note that define-application-frame 
                                   ; will interpret these values as spacing..
                               (100 stop-recording)))))))

(defun run-happy-grandparents ()
  (let* ((w 400) 
         (h 400)
         (frame (make-application-frame 'happy-grandparents :width w :height h)))
    (run-frame-top-level frame)))

(bt:make-thread #'run-happy-grandparents :name "The only obscene profit is a small one.")

;; btw, working in the CLIM-INTERNALS package can save you from having to import a bunch of nonsense
```

["jackdaniel: that reminds me, is mcclim thread-safe? I'd *like* to experiment from a different thread, but that's another chapter I have yet to reach (metaphorically speaking)"](http://irclog.tymoon.eu/freenode/%23clim?around=2016-07-09T14:34:51&types=mnaot#1468074891)

You can spin up as many applications in as many threads as you would like and should run into no issues. I don't think anyone knows *for sure* if McCLIM itself is threadsafe, or what that would even mean in the general case. We can probably help you out if you have a specific request, ie, you would like to return values from one thread into another thread (in CLIM terms, across applications).
