### ISSUE TITLE
CCL font/general rendering speed - possible fix

### ISSUE THREAD

**Issue by phoe-krk** [robert-strandh/McCLIM#50]
After some collaborative hacking with @marcmos we found that the issue can be relieved by changing a CCL internal static variable `**ccl::*ns-per-tick***` .

CCL seems to be spending most of its "slowness" time sleeping in its internal `**%nanosleep**` function; we can "wake it up" either by reducing that variable's value or moving the mouse.

```common-lisp
;; CCL-specific code
(setf ccl::*ns-per-tick* (/ ccl::*ns-per-tick* 1000))

(ql:quickload :mcclim)
(ql:quickload :mcclim-fonts/truetype)
(ql:quickload :clim-examples)

(clim-demo:demodemo)
```

Within the CLIM demo, the change is immediately visible when loading the main menu; there's a lot of slowness with the variable being at its original value, while the modified value gives me no delay when loading the menu.

There is also ~100x speedup at the Drawing Benchmark > random rectangle test - even when I don't load any code from the `mcclim-fonts/truetype` package.

Therefore I say that this is not an issue with font rendering per se, as @marcmos noted out to me before, but rather with the way CCL handles threads and its `**%nanosleep**` function. Sounds like a CCL bug for me.

**Comment by gabriel-laddel** [comment]
Hotness.

**Comment by phoe-krk** [comment]
@gabriel-laddel https://github.com/sharplispers/clx/pull/31 is the CLX fix that I offer.

As a temporary workaround, when loading McCLIM you can once do a `(setf ccl::*ns-per-tick* (/ ccl::*ns-per-tick* 1000))` when loading McCLIM or actually in its rc file; I'm curious whether it will have any stability impact on McCLIM or CCL itself, other than perhaps a combination of a performance speedup and somewhat higher CPU usage. I say it's the favor of the first.

Or you can wait for the CLX fix.

Anyway, I think this issue is closable as it's completely not connected to McCLIM itself; I just wanted to give you all a heads-up.

**Comment by gabriel-laddel** [comment]
@phoe-krk Eh, let's leave it open until we get a test suite setup for all combinations of supported CL implementations and backends.

**Comment by phoe-krk** [comment]
Xach merged my changes (and my changes to the changes). McCLIM can have TrueType turned on by default now for CCL.

**Comment by robert-strandh** [comment]
Great news!  Thanks a lot for taking care of that!
