### ISSUE TITLE
pane is resized too much on output

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#66]
Steps to reproduce:
type `(climi::with-text-size (t 714) (princ "?"))` in the Listener – that will draw a big letter and resize the pane to fit. But it resizes too much (twice as much – the prompt should be at the very bottom of the pane, while it's in the middle).

**Comment by gas2serra** [comment]
Hi,
the problem is in  "seos-write-newline".
I'm going to send you a patch.

Alessandro
