### ISSUE TITLE
Text-field gadget doesn't inherit text-style from pane

### ISSUE THREAD

**Issue by Peytonien** [robert-strandh/McCLIM#70]
It doesn't appear that changing the text style of the text-field gadget works.
Test case:
```
(define-application-frame superapp ()
  ()
  (:panes
   (text :text-field
         :text-style (make-text-style :fix :roman :huge)))
  (:layouts
   (default text)))

(defun app-main ()
  (run-frame-top-level (make-application-frame 'superapp)))
```
Results in no change of the text style

**Comment by dkochmanski** [comment]
technically it does inherit (that is – the initarg gets correctly propagated to the text-field gadget) – investigating

**Comment by dkochmanski** [comment]
as a side note, goatee text-field implementation doesn't allocate space properly (is basically a junk)
