### ISSUE TITLE
doc: provide doc-op for the system

### ISSUE THREAD

**Issue by dkochmanski** [robert-strandh/McCLIM#79]
If we'll also have a html path, we could fix the hyperclim.lisp path to point to something local.

// note for myself: to access asdf components:

```
(asdf:component-pathname (asdf:find-component :clamber "doc.html"))
```

**Comment by yaroe** [comment]
"hyperclim" that is the annotated html version of the spec could be the one that is maintained (anotations) via git here. As of now it is at  http://bauhh.dyndns.org:8000/clim-spec.
There could be  a tool for building an up-to-date pdf version via the asdf doc-op
