### ISSUE TITLE
Problems with StumpWM

### ISSUE THREAD

**Issue by ecraven** [robert-strandh/McCLIM#85]
I run stumpwm, the following program

```
;;; -*- Mode: Lisp; Package: CLIM-USER; Base: 10; Lowercase: Yes -*-
(ql:quickload 'mcclim)
(in-package :clim-user)
(define-application-frame test ()
  ()
  (:menu-bar nil)
  (:panes
   (string :application :scroll-bars nil :text-style '(:fix :bold :very-large) :display-function 'draw-string))
  (:layouts
    (main
     (vertically () string))))


(defmethod draw-string ((application test) stream)
  (format stream "test")
  (terpri stream))

#||
(setq test-app (make-application-frame 'test))
(run-frame-top-level test-app)
||#
```

results in 
![clim](https://cloud.githubusercontent.com/assets/215510/18233386/7e2270d0-72e6-11e6-80d3-4a0de9b6bf34.jpg)

It seems the width/height is not set correctly. If I pass explicit width/height to `make-application-frame`, things work fine.

Is there anything I'm missing to force a re-display after the configure-notify?

**Comment by gas2serra** [comment]
Hi, 
in an application-pane, all output is recorded. In your case, the "draw-text" function is called only once . When you or stumpwm resizes the window, the output does not change.

There are several "solutions":

- define a new pane without output-recording
- using scrollbars
- using ":end-of-line-action :allow" initarg 

```
(define-application-frame test ()
  ()
  (:menu-bar nil)
  (:panes
   (string :application
	   :scroll-bars nil
	   :text-style '(:fix :bold :very-large)
	   :end-of-line-action :allow
	   :display-function 'draw-string
	   ))
  (:layouts
    (main
     (vertically () string))))
```

What do you really need?

**Comment by dkochmanski** [comment]
closing as non-issue. calling redisplay-pane should  be enough to reflow the pane.
