### ISSUE TITLE
End of output not displayed

### ISSUE THREAD

**Issue by robert-strandh** [robert-strandh/McCLIM#94]
In the following example, when the command "fill" has been executed,
the last two lines of the display are not shown.  Instead a black area
is shown:
```common-lisp
(cl:in-package #:common-lisp-user)

(defpackage #:pane-size
  (:use :clim-lisp :clim)
  (:export #:pane-size))

(in-package #:pane-size)

(define-application-frame pane-size ()
  ()
  (:panes
   (text :application
	 :scroll-bars nil
	 :width 800
	 :display-time nil)
   (inter :interactor :width 800 :height 100))
  (:layouts
   (:default (vertically ()
	       (scrolling (:scroll-bars t) text)
	       inter))))
			   
(defun pane-size ()
  (run-frame-top-level (make-application-frame 'pane-size)))

(define-pane-size-command (com-quit :name t) ()
  (frame-exit *application-frame*))

(define-pane-size-command (com-fill :name t) ()
  (let* ((out (find-pane-named *application-frame* 'text))
	 (medium (sheet-medium out))	      
	 (text-style (make-text-style :sans-serif :roman nil)))
    (window-clear out)
    (with-text-style (medium text-style)
      (with-text-size (medium :huge)
	(loop for i from 1 to 20
	      do (format out "~d~%" i))))))
```

**Comment by dkochmanski** [comment]
confirmed

**Comment by robert-strandh** [comment]
In the example, REPLAY-OUTPUT-RECORD is never called on the displayed
output record containing "20".

REPLAY-OUTPUT-RECORD is called on the the displayed output record
containing "19", but with a restrictive clipping region.  The Y
coordinate of that output record starts at 4311/8 (around 539) and the
clipping region has its maximum Y coordinate at 544.  This is why only
a few pixels are shown of this output record.

Also, when REPLAY-OUTPUT-RECORD is called on the output history itself
(which is an instance of the class STANDARD-TREE-OUTPUT-HISTORY), the
clipping region also has a maximum Y coordinate at 544, so this
clipping region is going to restrict the replay of the children, which
is why the result is what it is.

I suspect that there is nothing wrong with the code for the output
history and instead, it has to do with whatever function calls
REPLAY-OUTPUT-RECORD on the output history.  The clipping region that
is passed is too small.

**Comment by robert-strandh** [comment]
Further investigation reveals that REPLAY-OUTPUT-RECORD is called from
REPLAY which is called from STREAM-REPLAY and STREAM-REPLAY is already
called with the clipping region that is too small.

**Comment by robert-strandh** [comment]
STREAM-REPLAY is called from HANDLE-REPAINT and HANDLE-REPAINT is
already called with the clipping region that is too small.

**Comment by robert-strandh** [comment]
HANDLE-REPAINT is called from REPAINT-SHEET which is already called
with the clipping region that is too small.

**Comment by robert-strandh** [comment]
REPAINT-SHEET is called from HANDLE-EVENT when it is handling an event
of type WINDOW-REPAINT-EVENT, which is where it gets the region from,
so it must be the case that when the WINDOW-REPAINT-EVENT is created,
it is created with the wrong region.

**Comment by robert-strandh** [comment]
It appears that when MAKE-RECTANGLE* is called from within
EVENT-HANDLER (in the CLX backend) in order to create a
WINDOW-REPAINT-EVENT, it is passed the wrong height.

**Comment by gas2serra** [comment]
Hi,
the problem is due to the strange behavior of  Coordinate Swizzling. The height of the window is correct but it is smaller that the height of the sheet. The window of the border-pane around the application-pane is correctly resized. The error is that this resizing is not propagated to the window of the application-pane.
It is really difficult to understand what is happening. Maybe, I insert the bug when I moved the code of Coordinate Swizzling... if so, I'm sorry. 
I'm going to fix it.
