### ISSUE TITLE
Listener scrolls bottom line out of sight after resizing

### ISSUE THREAD

**Issue by stacksmith** [robert-strandh/McCLIM#98]
Opening a listener, resizing and using it for a while is nearly impossible: the active line scrolls out of visible area.
Using sbcl.

**Comment by gabriel-laddel** [comment]
@stacksmith  Not sure what you mean by this. 

1) Perhaps you are using an old version: https://github.com/robert-strandh/McCLIM/issues/32

2) Use (CLIM-LISTENER::COM-CLEAR-OUTPUT-HISTORY) via ",clear output history" at the listener.

3) please describe in more detail because idk wtf?

**Comment by dkochmanski** [comment]
Hey, thanks for reporting this. I can't reproduce your problem. Could you check, if it isn't fixed in the main repository? To do that, please clone the "master" branch to `~/quicklisp/local-projects/`, issue `(ql:register-local-projects)` and load the listener again.

**Comment by stacksmith** [comment]
Cloning fixed it.  The prompt lines up to the bottom now.
There is still a tiny glitch:
- hit ```Enter``` until the window is filled to the bottom with prompts;
- enlarge the window by about half a line's height
- hit ```Enter```.  The prompt lines up to the bottom, but the cursor is halfway below the visible area.
However, typing anything at this point corrects the cursor position, so it is very minor.
